
set BUILT_VERSION="1.2.0"
set PROJECT_NAME="SRVoting"

set RELEASE_BUILD_DIR=".\%PROJECT_NAME%\bin\Release"
set MAIN_DLL="%RELEASE_BUILD_DIR%\%PROJECT_NAME%.dll"

set OUTPUT_DIR=".\build\%PROJECT_NAME%_v%BUILT_VERSION%"
mkdir %OUTPUT_DIR%

copy %MAIN_DLL% %OUTPUT_DIR%
